# Generated by Django 5.1.4 on 2025-01-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
        ('postit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='paperFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.paper'),
        ),
    ]
