# Generated by Django 5.1.4 on 2025-01-08 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "receiverName",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("receiverTel", models.CharField(blank=True, max_length=11, null=True)),
                ("receivingDate", models.DateField()),
                ("receivingStat", models.IntegerField(default=0)),
                ("viewStat", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "hostFK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="paper_host",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitingUser",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inviting_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiverFk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="paper_receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
