# Generated by Django 5.1.4 on 2025-01-18 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('receiverName', models.CharField(blank=True, max_length=15, null=True)),
                ('receiverTel', models.CharField(blank=True, max_length=11, null=True)),
                ('receivingDate', models.DateField()),
                ('receivingStat', models.IntegerField(default=0)),
                ('viewStat', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueryIndexTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query', models.JSONField(default=dict)),
                ('type', models.CharField(choices=[('COLOR', '색상'), ('THEME', '테마'), ('SIZE', '사이즈'), ('RATIO', '비율')], max_length=6)),
                ('is_vip', models.BooleanField(default=False)),
            ],
        ),
    ]
