# Generated by Django 5.1.4 on 2025-01-09 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='receiverFk',
        ),
        migrations.AddField(
            model_name='paper',
            name='receiverFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paper_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
