# Generated by Django 5.1.4 on 2025-01-18 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('code', models.UUIDField(default=uuid.uuid4, null=True)),
                ('danger', models.IntegerField(default=0)),
                ('context', models.TextField()),
                ('location', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'heart',
            },
        ),
    ]
