# Generated by Django 5.1.4 on 2025-01-09 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper', '0002_remove_paper_receiverfk_paper_receiverfk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('context', models.TextField()),
                ('danger', models.IntegerField(default=0)),
                ('paperFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.paper')),
                ('userFK', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'heart',
            },
        ),
    ]
