# Generated by Django 5.1.4 on 2025-01-09 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0001_initial'),
        ('paper', '0002_remove_paper_receiverfk_paper_receiverfk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heart',
            new_name='HeartModel',
        ),
    ]
