# Generated by Django 5.1.4 on 2025-01-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heart', '0001_initial'),
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='colorFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_color', to='paper.queryindextable'),
        ),
        migrations.AddField(
            model_name='heart',
            name='paperFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.paper'),
        ),
    ]
