# Generated by Django 5.1.4 on 2025-01-10 05:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0003_rename_heartmodel_heart'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
