# Generated by Django 5.1.4 on 2025-01-10 05:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0004_heart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
