# Generated by Django 5.1.4 on 2025-01-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0005_alter_heart_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
