# Generated by Django 5.1.4 on 2025-01-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0006_heart_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heart',
            old_name='index',
            new_name='location',
        ),
    ]
