# Generated by Django 5.1.4 on 2025-01-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_created_at_user_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
