# Generated by Django 5.1.4 on 2025-01-10 05:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
