# Generated by Django 5.1.4 on 2025-01-10 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
