name: Django On-demand Server Deploy
run-name: ${{ github.actor }}

on:
  push:
    branches: "dev"
  pull_request:
    branches: "dev"

jobs:
  ci:
    name: "Django CI"
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - run: ls -al
