name: Django On-demand Server Deploy
run-name: ${{ github.actor }}

on:
  push:
    branches: "dev"
  pull_request:
    branches: "dev"

jobs:
  ci:
    name: "Django CI"
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Matrix Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.4.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Make Virtual Environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

        
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Make .env file
      run: |
        cd rollpe
        touch ./.env
        echo "${{secrets.ENV_FILE}}" > ./.env
        cat ./.env

    - name: Run Django Test
      run: |
        python3 manage.py test

        
